package com.macurexdashboard.repo;

import java.util.Set;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;

import com.macurexdashboard.entity.EInvoiceVO;

public interface EInvoiceRepo extends JpaRepository<EInvoiceVO, Long> {

	@Query(nativeQuery = true, value = "SELECT  HEADING,TYPE, SUM(VALUE)VALUE\r\n"
			+ "FROM (\r\n"
			+ "SELECT 'PURCHASE VALUE' as HEADING,'SGST'TYPE, sum(PB.totamt)VALUE \r\n"
			+ "FROM  PURCHOBASIC PB \r\n"
			+ "WHERE  PB.cancel='F' \r\n"
			+ "and PB.TSTATE='KARNATAKA'\r\n"
			+ "and PB.LOCID<>10027000189569  \r\n"
			+ "and PB.LOCID<>10016000096880\r\n"
			+ "and PB.LOCID<>10023000049937\r\n"
			+ "AND PB.GRNDT BETWEEN \r\n"
			+ "    TO_DATE(?1,'YYYY-MM-DD HH24:MI:SS')\r\n"
			+ "AND TO_DATE(?2,'YYYY-MM-DD HH24:MI:SS')\r\n"
			+ "and PB.UNDER=?3\r\n"
			+ "union\r\n"
			+ "SELECT 'PURCHASE VALUE' as HEADING,'IGST'TYPE, sum(PB.totamt)VALUE \r\n"
			+ "FROM  PURCHOBASIC PB \r\n"
			+ "WHERE  PB.cancel='F' \r\n"
			+ "and PB.TSTATE<>'KARNATAKA'\r\n"
			+ "and PB.LOCID<>10027000189569  \r\n"
			+ "and PB.LOCID<>10016000096880\r\n"
			+ "and PB.LOCID<>10023000049937\r\n"
			+ "AND PB.GRNDT BETWEEN \r\n"
			+ "    TO_DATE(?1,'YYYY-MM-DD HH24:MI:SS')\r\n"
			+ "AND TO_DATE(?2,'YYYY-MM-DD HH24:MI:SS')\r\n"
			+ "and PB.UNDER=?3\r\n"
			+ "UNION\r\n"
			+ "SELECT 'PURCHASE VALUE' as HEADING,'CONSUMABLES'TYPE, sum(PB.totamt)VALUE \r\n"
			+ "FROM  PURCHOBASIC PB \r\n"
			+ "WHERE  PB.cancel='F' \r\n"
			+ "and PB.LOCID=10027000189569 \r\n"
			+ "AND PB.GRNDT BETWEEN \r\n"
			+ "    TO_DATE(?1,'YYYY-MM-DD HH24:MI:SS')\r\n"
			+ "AND TO_DATE(?2,'YYYY-MM-DD HH24:MI:SS')\r\n"
			+ "and PB.UNDER=?3\r\n"
			+ "UNION\r\n"
			+ "SELECT 'PURCHASE VALUE' as HEADING,'CONSUMABLES'TYPE, sum(PB.totamt)VALUE \r\n"
			+ "FROM  PURCHOBASIC PB \r\n"
			+ "WHERE  PB.cancel='F' \r\n"
			+ "and PB.LOCID=10016000096880 \r\n"
			+ "AND PB.GRNDT BETWEEN \r\n"
			+ "    TO_DATE(?1,'YYYY-MM-DD HH24:MI:SS')\r\n"
			+ "AND TO_DATE(?2,'YYYY-MM-DD HH24:MI:SS') \r\n"
			+ "and PB.UNDER=?3\r\n"
			+ "union \r\n"
			+ "SELECT 'PURCHASE VALUE' as HEADING,'IMPORTVAL'TYPE, sum(pb.totlandvalue)VALUE\r\n"
			+ "FROM  grnhdr PB ,partymast p \r\n"
			+ "WHERE  PB.cancel='F' \r\n"
			+ "and P.STATE<>'INDIA'\r\n"
			+ "and PB.LOCID<>10023000049937\r\n"
			+ "and P.PARTYMASTID=PB.SUPPLIERID\r\n"
			+ "AND PB.docdate BETWEEN \r\n"
			+ "    TO_DATE(?1,'YYYY-MM-DD HH24:MI:SS')\r\n"
			+ "AND TO_DATE(?2,'YYYY-MM-DD HH24:MI:SS')\r\n"
			+ "and PB.UNDER=?3\r\n"
			+ "UNION\r\n"
			+ "SELECT 'PURCHASE VALUE' as HEADING,'CAPTIAL'TYPE, sum(pb.totlandvalue)VALUE\r\n"
			+ "FROM  grnhdr PB ,partymast p \r\n"
			+ "WHERE  PB.cancel='F' \r\n"
			+ "and P.STATE<>'INDIA'\r\n"
			+ "and PB.LOCID=10023000049937 \r\n"
			+ "and P.PARTYMASTID=PB.SUPPLIERID\r\n"
			+ "AND PB.docdate BETWEEN \r\n"
			+ "    TO_DATE(?1,'YYYY-MM-DD HH24:MI:SS')\r\n"
			+ "AND TO_DATE(?2,'YYYY-MM-DD HH24:MI:SS')\r\n"
			+ "and PB.UNDER=?3\r\n"
			+ "union\r\n"
			+ "SELECT 'PURCHASE VALUE' as HEADING,'CAPTIAL'TYPE, sum(PB.totamt)VALUE \r\n"
			+ "FROM  PURCHOBASIC PB \r\n"
			+ "WHERE  PB.cancel='F' \r\n"
			+ "and PB.LOCID=10023000049937 \r\n"
			+ "AND PB.GRNDT BETWEEN \r\n"
			+ "    TO_DATE(?1,'YYYY-MM-DD HH24:MI:SS') \r\n"
			+ "AND TO_DATE(?2,'YYYY-MM-DD HH24:MI:SS')\r\n"
			+ "and PB.UNDER=?3\r\n"
			+ "UNION\r\n"
			+ "SELECT 'PURCHASE VALUE' as HEADING,'LABOUR'TYPE, sum(PB.BASICAMT )VALUE \r\n"
			+ "FROM  subgrnBASIC PB \r\n"
			+ "WHERE  PB.cancel='F' \r\n"
			+ "AND PB.GRNDT BETWEEN \r\n"
			+ "    TO_DATE(?1,'YYYY-MM-DD HH24:MI:SS')\r\n"
			+ "AND TO_DATE(?2,'YYYY-MM-DD HH24:MI:SS')\r\n"
			+ "and PB.UNDER=?3\r\n"
			+ ")\r\n"
			+ "group by  HEADING,TYPE")
	Set<Object[]> getPurchaseDashboardDetails(String formDate,String toDate,String under);
	

	@Query(nativeQuery = true, value = "select 'Break Down' as type, sum(open) AS Noofbreakdown,case when(sum(open)-sum(close))>0 then sum(open)-sum(close) else 0 end as OPEN, sum(close) AS CLOSE from(\r\n"
			+ "select count(*) as open,0 as close from macbrkdrpbasic\r\n"
			+ "where docdt  BETWEEN \r\n"
			+ "          TO_TIMESTAMP(?1,'YYYY-MM-DD HH24:MI:SS.FF3')\r\n"
			+ "      AND TO_TIMESTAMP(?2,'YYYY-MM-DD HH24:MI:SS.FF3')\r\n"
			+ "union\r\n"
			+ "select 0 as open, count(*) as close from macbrkdrpbasic where macbrkdrpbasicid in(select distinct BRKRDOCNO from rectificationdet where docdt BETWEEN \r\n"
			+ "          TO_TIMESTAMP(?1,'YYYY-MM-DD HH24:MI:SS.FF3')\r\n"
			+ "      AND TO_TIMESTAMP(?2,'YYYY-MM-DD HH24:MI:SS.FF3')))")
	Set<Object[]> getMaintenanceDetails(String formDate,String toDate);


}
